//
//  StripePluginClient.m
//  Runner
//
//  Created by Jack Liu on 7/3/2019.
//  Copyright © 2019 The Chromium Authors. All rights reserved.
//

#import "StripePluginClient.h"

static StripePluginClient *instance;

@interface StripePluginClient() {
    NSString *publishableKey, *appleMerchantId;
}
@end

@implementation StripePluginClient

/**
 Create StripePliginClient instance by publishable key and backend server url

 @param publishableKey Publisable key generated by Stripe
 @return StripePliginClient share instance
 */
+ (id)createShareInstanceWithPublishableKey:(NSString * _Nonnull)publishableKey {
    if (!instance) {
        instance = [[StripePluginClient alloc] initWithWithPublishableKey:publishableKey appleMerchantId:nil];
    }
    return instance;
}

+ (id)createShareInstanceWithPublishableKey:(NSString * _Nonnull)publishableKey appleMerchantId:(NSString * _Nonnull)appleMerchantId {
    if (!instance) {
        instance = [[StripePluginClient alloc] initWithWithPublishableKey:publishableKey appleMerchantId:appleMerchantId];
    }
    return instance;
}

+ (id)getShareInstance {
    return instance;
}

- (id)initWithWithPublishableKey:(NSString * _Nonnull)key appleMerchantId:(NSString * _Nullable)merchantId {
    self = [super init];
    if (self) {
        publishableKey = key;
        appleMerchantId = merchantId;
        
        if (publishableKey) {
            [Stripe setDefaultPublishableKey:publishableKey];
        }
    }
    return self;
}

- (NSString *)getPublishableKey {
    return publishableKey;
}

- (NSString *)getAppleMerchantId {
    return appleMerchantId;
}
@end
